name = "nord-theme"
display-name = "Nord Theme"
description = "An arctic, north-bluish color palette."
icon = "icon.png"
version = "0.1.1"
author = "ItzSwirlz,niacdoial"
repository = "https://github.com/niacdoial/nord-light-lapce"
color-themes = ["nord-dark.toml", "nord-light.toml"]
